### ISSUE TITLE
pure alphabetical sorting

### ISSUE THREAD

**Issue by acarl005** [monsterkodi/color-ls#1]
The output groups directories first. An option to have simple alphabetical sorting (like the native ls command) would be nice.

**Comment by monsterkodi** [comment]
Hi Andy,
I probably need some more motivation before I implement this. 
Can you please give me an example when or why that might be useful?
And how would you call that option?
Thanks in advance,
yours kodi

**Comment by monsterkodi** [comment]
Well, I can't see that I will ever use this, but it was easily done:
The latest version (1.1.2) has a hidden option --alphabetical or -A to do what you requested.
Let me know if it doesn't work as expected.
But I am still curious: if you convince me that this is really useful, I will unhide the option :-)

**Comment by monsterkodi** [comment]
Hi Andy, I guess this will remain a hidden option then :-)

**Comment by monsterkodi** [comment]
And thanks for the star, BTW!

**Comment by acarl005** [comment]
Hi, thanks for the option!

It's what I'm most used to. After using `/bin/ls -FGlAhp` for so long, my brain most instinctively looks for things alphabetically regardless of whether they are directories or not. It's not more inherently "useful", just the most comfortable. I appreciate it!

**Comment by monsterkodi** [comment]
You are welcome. Glad you like it.
I can see from your fork that you want it to look and behave exactly like the old ls :-)
Good work, btw.
